CREATE TABLE IF NOT EXISTS t_projet (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) DEFAULT NULL,
	description VARCHAR(255) DEFAULT NULL,
	adresse VARCHAR(255) DEFAULT NULL,
	dateCreation DATE DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;